version: '3.8'

services:
  masterclass-lp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_GTM_ID=${NEXT_PUBLIC_GTM_ID}
        - NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_GTM_ID=${NEXT_PUBLIC_GTM_ID}
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID}
    restart: unless-stopped

  # Development service
  masterclass-lp-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    ports:
      - "3001:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - NEXT_PUBLIC_GTM_ID=${NEXT_PUBLIC_GTM_ID}
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID}
    restart: unless-stopped
    profiles:
      - dev